version: "3.9"
name: text-comparison

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: comparison-backend:v1
    container_name: backend
    env_file:
      - backend/.env  
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: comparison-frontend:v1
    container_name: frontend
    environment:
      API_URL: http://backend:8000
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
